### ISSUE TITLE
Permission denied errors when running kubectl commands

### ISSUE THREAD

**Issue by rprakashg** [bitnami/bitnami-docker-kubectl#23]
**Description**
I'm using this image to run some kubectl commands against cluster from a gitlab CI pipeline. 

from the pipeline I read the secrets from repo, interact with API that issues token to work with cluster and 

Commands below are run to set the kubeconfig to work with the k8s cluster 
kubectl config set-credentials "${K8S_USER}" --token="${sToken}"
echo "[INFO] Set kubetl config credentials to ${K8S_USER} for cluster"
 

#Commands to set the kubeconfig to connect to the cluster
kubectl config set-cluster "${K8S_CLUSTER}" --server="${K8S_SERVER_URL}"
kubectl config set-cluster "${K8S_CLUSTER}" --insecure-skip-tls-verify=true
kubectl config set-context "${K8S_CONFIG_CONTEXT}" --cluster="${K8S_CLUSTER}" --user="${K8S_USER}"
kubectl config use-context "${K8S_CONFIG_CONTEXT}"

All these commands fail with error mkdir permission denied. Here is the output from pipeline logs
error: mkdir /.kube: permission denied
[INFO] Set kubetl config credentials to svc_det_dev_cicd for conducktor platform.
error: mkdir /.kube: permission denied
error: mkdir /.kube: permission denied
error: mkdir /.kube: permission denied

**Comment by migruiz4** [comment]
Hi @rprakashg,

The 'permission denied' is caused by user 1001 not having permission to create a new folder at the $HOME path, which defaults to `/`.

To solve this issue, you could either mount a data volume at `/.kube` which GitLab CI should support: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#example-1-adding-a-data-volume

Alternatively, you could also solve the permission issue by changing your $HOME path from `/` to `/tmp`. That will change the config path from `/.kube/config` to `/tmp/.kube/config`
