### ISSUE TITLE
Update curl to at least 7.76.0 so --fail-with-body is available

### ISSUE THREAD

**Issue by rouke-broersma** [bitnami/bitnami-docker-kubectl#35]
**Description**

**Steps to reproduce the issue:**

 -Try to use `curl --fail-with-body`

**Describe the results you received:**

 - `option --fail-with-body unknown` 

**Describe the results you expected:**

Curl is executed with new option `--fail-with-body`

**Comment by carrodher** [comment]
We are installing `curl` using the system packages, since we build the images on a daily basis, the latest version available in the distro is going to be installed. In this case, this is curl 7.64.0 is the latest available in Debian:
```
I have no name!@4895b8a8d03b:/$ apt -s install curl
NOTE: This is only a simulation!
      apt needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

When `curl` is updated in the distro, it will be updated in the new tags of this bitnami/kubectl container image. In the meantime, you should manually install the new `curl` version in your container
