### ISSUE TITLE
No image for v1.24+

### ISSUE THREAD

**Issue by itspngu** [bitnami/bitnami-docker-kubectl#42]
### Name and Version

bitnami/kubectl:1.24

### What steps will reproduce the bug?

1. Install the Velero (or anything that incorporates `bitnami/kubectl` based on k8s version in the same fashion) Helm Chart
2. UH!
3. imagePullError

### What is the expected behavior?

Kubernetes v1.24.0 has been released 9 days ago at the time of writing this, I'd have expected to see a matching `bitnami/kubectl` by now.

### What do you see instead?

No `bitnami/kubectl:1.24`.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our tracking system but since it is a new major version (it is a new branch), it will require some manual changes on our side and it is not going to be released automatically.
That's the reason why it is being delayed.

We will update this issue once released.

**Comment by carrodher** [comment]
Kubectl 1.24 container image was released, you can find it in DockerHub and other registries as usual.

The related commit in this repo is https://github.com/bitnami/bitnami-docker-kubectl/commit/5e8650ba1df2e817b20e9adadd8cdcd2d2750209

Feel free to create a new ticket if you find any issues.
